### Appendix A: NumpyとMatplotlibの簡単公式

**Numpy**（[参考リンク](http://www.turbare.net/transl/scipy-lecture-notes/intro/numpy/index.html)）と**Matplotlib**（[参考リンク](http://www.turbare.net/transl/scipy-lecture-notes/intro/matplotlib/matplotlib.html)）という**科学技術計算用の外部モジュール**（[参考リンク](http://www.turbare.net/transl/scipy-lecture-notes/intro/)）を使いましょう。numpy モジュールの全関数を使うためには，numpyを呼び出さなければなりません(輸入=import)。**プログラムの一番最初**に、通常、以下のようにしてnumpy呼び出します：

*****
**＜公式A-1a＞**  

**import numpy as np**  

意味：**numpyモジュールをnpという省略形の名前で呼び出します。**これで，numpyモジュールに登録されている全ての関数(，属性，予約語等)を使うことができます。なお，numpy関数は  

```
np.関数名(引数)   
```

という形で使います。numpy（np）の関数名(引数)という意味です（npの後のピリオド「.」は「の」という意味です）。

> 【例】sin(値)やcos(値)を使いたいとき
```
import numpy as np  #←プログラム内で１回だけ書けばよい
...  
np.sin(値)  
np.cos(値)  
```

*****

*****  
**＜公式A-1b＞**  

**from numpy import *関数名1*, *関数名2*, ..., *予約語1*, *予約語2*, ...**  
 
意味：**numpyモジュールに定義されている特定の関数や予約語:*関数名1*, *関数名2*, ..., *予約語1*, *予約語2*, ...を呼び出します**。この場合，呼び出されたnumpy関数や予約語は，＜公式A-1a＞のように，関数名の前に「np.」をつける必要はありません。
```
関数名(引数)   
```
という形で使います。
> 【例】sin(値)，cos(値)，tan(値)を使いたいとき
```
from numpy import sin, cos  #←プログラム内で１回だけ書けばよい
...
sin(値)
cos(値)
tan(値)
```

*****

*****  
**＜公式A-1c＞**  

**from numpy import ***  
 
意味：**numpyモジュールに定義されているすべての関数や予約語を呼び出します**。この場合，呼び出されたnumpy関数や予約語は，＜公式A-1a＞のように，関数名の前に「np.」をつける必要はありません。ただし，このインポートのやり方は**推奨されません**ので、なるべく**使わないように**しましょう。
```
関数名(引数)   
```
という形で使います。
> 【例】sin(値)，cos(値)，tan(値)を使いたいとき
```
from numpy import *  #←プログラム内で１回だけ書けばよい
...
sin(値)
cos(値)
tan(値)
```

*****

**※) 以下必要な公式を書きますが、＜公式A-1a＞でnumpyモジュールが(npとして)インポートされた形式で書くことにします。 ＜公式A-1b＞のように特定の関数のみをインポートした場合は、「np.」を省略してください。**

*****
**＜公式A-2＞**  

**np.array(リスト)**  

意味：リストを**ndarray**という**Numpy配列**に変換します。**Numpy配列**というのは、大まかに次の性質を持っている配列です（Pythonのリストのようなものですが振る舞いが違います）：  
1. **同じ長さ(要素数)**のNumpy配列の間で**四則演算**や**べき乗演算**ができます。  
```
In [1]:  a = np.array([12,21,16])
            b = np.array([3, 7, 4])          
In [2]:  a + b
Out[2]:  array([15, 28, 20])
In [3]:  a - b
Out[3]:  array([ 9, 14, 12])
In [4]:  a * b
Out[4]:  array([ 36, 147,  64])
In [5]:  a / b
Out[5]:  array([ 4.,  3.,  4.])
In [6]:  b ** 3
Out[6]:  array([ 27, 343,  64])  
```
2. **関数の引数としてnumpy配列**を使用すると、各々の要素にその関数が適応された**numpy配列を返します**。  
```
In [7]:  def f(x, y):
                return x**2 + y**2
In [8]:  f(a, b)
Out[8]:  array([153, 490, 272])
```

*****

*****
**＜公式A-3＞**  

**np.arange(値1, 値2, 値3)**  

意味：**値1から、値3で指定された間隔の、値2の１つ手前の値までのNumpy配列を作成します。値1, 値2, 値3は整数でも浮動小数店でも構いません。**  
※) 値1と値3は省略可能ですが，ややこしいので省略しないほうがいいと思います。  

> 【例】
```
In [9]:  np.arange(1, 3.1, 0.1)
Out[9]:  array([ 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9,  
                 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 
                 3. ])
```

*****

*****
**＜公式A-4＞**  

**np.pi**  

意味：**円周率$\pi$の値です。**  
※) 関数ではなくて**予約語**です。`np.pi()`とするとエラーになりますので注意してください。
*****

*****
**＜公式A-5a＞**  

**np.radians(値)**　　

意味：**60分法(度)で表された角の値を、ラジアンの角の値に変換します（引数はnumpy配列でも可）。**

*****
**＜公式A-5b＞**  

**np.degrees(値)**　

意味：**ラジアンで表された角の値を、60分法(度)の角の値に変換します（引数はnumpy配列でも可）。**
*****

*****
**＜公式A-6a＞**  

**np.sin(値)**　　

意味：**ラジアンで表された角の値の $\sin$ を求めます（引数はnumpy配列でも可）。**  
*****
**＜公式A-6b＞**  

**np.cos(値)**　　

意味：**ラジアンで表された角の値の $\cos$ を求めます（引数はnumpy配列でも可）。**  
*****
**＜公式A-6c＞**  

**np.tan(値)**　　

意味：**ラジアンで表された角の値の $\tan$ を求めます（引数はnumpy配列でも可）。** 
*****  
> 【例】  
```
In [10]:  np.sin(np.pi/6)  
Out[10]:  0.49999999999999994  
In [11]:  np.sin(np.radians(30))  
Out[11]:  0.49999999999999994  
In [12]:  np.cos(np.pi/4)  
Out[12]:  0.70710678118654757  
In [13]:  np.cos(np.radians(45))  
Out[13]:  0.70710678118654757  
In [14]:  np.tan(np.pi/3)  
Out[14]:  1.7320508075688767  
In [14]:  np.tan(np.radians(60))  
Out[14]:  1.7320508075688767  
In [15]:  A = np.arange(0, 181, 10)
          A  
Out[15]:  array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100,  
                 110, 120, 130, 140, 150, 160, 170, 180])  
In [16]:  np.sin(np.radians(A))  
Out[16]:  array([  0.00000000e+00,   1.73648178e-01,   3.42020143e-01,
                   5.00000000e-01,   6.42787610e-01,   7.66044443e-01,
                   8.66025404e-01,   9.39692621e-01,   9.84807753e-01,
                   1.00000000e+00,   9.84807753e-01,   9.39692621e-01,
                   8.66025404e-01,   7.66044443e-01,   6.42787610e-01,
                   5.00000000e-01,   3.42020143e-01,   1.73648178e-01,
                   1.22464680e-16])
```

*****

*****
**＜公式A-7＞**  

**np.sqrt(値)**  

意味：**値のルートを求めます（引数はnumpy配列でも可）。** 
> 
【例】  
```
In [17]:  np.sqrt(2)  
Out[17]:  1.4142135623730951  
In [18]:  B = np.arange(0, 11, 1)
          B  
Out[18]:  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
In [19]:  np.sqrt(B)
Out[19]:  array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  
                  2.        ,  2.23606798,  2.44948974,  2.64575131,  
                  2.82842712,  3.        ,  3.16227766])
```

*****

*****
**＜公式A-8a＞**  

**import matplotlib.pyplot as plt**  

意味：**matplotlibパッケージのpyplotモジュールをpltという省略形の名前で呼び出します。**これで，pyplotモジュールに登録されている全ての関数(、属性、予約語等)を使うことができます。なお，matplotlib関数は  

```
plt.関数名(引数)   
```

という形で使います。
*****

*****  
**＜公式A-8b＞**  

**from matplotlib.pyplot import *関数名1*, *関数名2*, ..., *予約語1*, *予約語2*, ...**  
 
意味：**matplotlibパッケージのpyplotモジュールに定義されている特定の関数や予約語:*関数名1*, *関数名2*, ..., *予約語1*, *予約語2*, ...を呼び出します**。この場合，呼び出されたnumpy関数や予約語は，＜公式A-8a＞のように，関数名の前に「plt.」をつける必要はありません。
```
関数名(引数)   
```
という形で使います。
*****

**※) 以下必要な公式を書きますが、＜公式A-8a＞でmatplotlibパッケージのpyplotモジュールが(pltとして)インポートされた形式で書くことにします。 ＜公式A-8b＞のように特定の関数のみをインポートした場合は、「plt.」を省略してください。**

*****  
**＜公式A-9＞**  

**plt.figure()**  
**plt.plot(リスト1, リスト2)**  
**plt.xlabel('横軸ラベル名')**  
**plt.ylabel('縦軸ラベル名')**  

意味：**リスト1の各々のデータを*x*の値にリスト2の各々のデータを*y*の値にとった，$y = f(x)$の*x*-*y*グラフを描画します。このとき、横軸に指定の「横軸ラベル名」が、縦軸に指定の「縦軸ラベル名」が表示されます。なお、グラフは上描きされません。**
  
> plt.figure()の部分を、plt.figure(figsize=(整数1, 整数2))に書き換えると、グラフ横縦比を整数1:整数2にして描きます。例えば、plt.figure(figsize=(16, 9))とすると、ワイド画面比でグラフを描画します。

*****